### ISSUE TITLE
Versioning the module to avoid problems

### ISSUE THREAD

**Issue by ainestal** [terraform-community-modules/tf_aws_vpc#21]
Due to the improvement of the module there are some changes that will make some resources to be modified and/or removed and created. This can be problematic for different scenarios.

It would be nice to create tags (releases) so we can point to specific states of the module

**Comment by antonbabenko** [comment]
Fixed by pushing two new tags:

  - [v1.0.2](https://github.com/terraform-community-modules/tf_aws_vpc/tree/v1.0.2) - with NAT gateways
  - [v1.0.1](https://github.com/terraform-community-modules/tf_aws_vpc/tree/v1.0.1) - before NAT gateways were added (I suppose you need to use this one, as resources were renamed after this commit).

Tagging is not part of github merge process, so I sometimes forget to do this.

Also, remember that you can specify git sha as ref in module. `ref` - The ref to checkout. This can be a branch, tag, commit, etc.
