### ISSUE TITLE
Master and  tags

### ISSUE THREAD

**Issue by lgallard** [terraform-community-modules/tf_aws_vpc#32]
Hi,

I wonder how you handle master branch and tags. Can I consider master as stable? Or should I point to a specific tag. If so, last tag was v1.0.2 and after that there have been other commits...will be there v.1.0.3 with those commits?

Thanks in advanced!

**Comment by antonbabenko** [comment]
Usually `master` branch is safe to use, because code there is backward compatible (again "usually"). Tagging is done ad-hoc and there is no strong procedure for maintainer to follow. I normally try to tag if code in module has chance to diverge and become not backward compatible at some point.

Closing for now, but please open other specific issues in the future, if we should improve things in some way.

**Comment by lgallard** [comment]
Thanks and sorry for opening the issue for ask.

Best regards!
